<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Description>Microsoft Service Fabric core libraries.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Autofac.ServiceFabric" Version="5.0.0" />
        <PackageReference Include="Cogito.Autofac" Version="6.1.3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cogito.ServiceFabric\Cogito.ServiceFabric.csproj" />
    </ItemGroup>

</Project>
