<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Description>Extensions to the Service Fabric services classes.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cogito.ServiceFabric.Autofac\Cogito.ServiceFabric.Autofac.csproj" />
        <ProjectReference Include="..\Cogito.ServiceFabric.Services\Cogito.ServiceFabric.Services.csproj" />
        <ProjectReference Include="..\Cogito.ServiceFabric\Cogito.ServiceFabric.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.ServiceFabric" Version="11.7.157" />
      <PackageReference Include="Microsoft.ServiceFabric.Data" Version="8.7.157" />
      <PackageReference Include="Microsoft.ServiceFabric.Data.Interfaces" Version="8.7.157" />
      <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="8.7.157" />
      <PackageReference Include="Microsoft.ServiceFabric.FabricTransport.Internal" Version="8.7.157" />
    </ItemGroup>

</Project>
