<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Description>Extensions to the Service Fabric services classes.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.ServiceFabric" Version="11.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Data" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Data.Extensions" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Data.Interfaces" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.FabricTransport.Internal" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Services" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Services.Remoting" Version="8.7.157" />
        <PackageReference Include="System.Collections.Immutable" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cogito.ServiceFabric\Cogito.ServiceFabric.csproj" />
    </ItemGroup>

</Project>
