<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Description>Cogito extensions to the Microsoft Service Fabric core libraries.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Castle.Core" Version="5.2.1" />
        <PackageReference Include="Cogito.Core" Version="3.1.29" />
        <PackageReference Include="Microsoft.ServiceFabric" Version="11.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Data" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Data.Extensions" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Data.Interfaces" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="8.7.157" />
        <PackageReference Include="Microsoft.ServiceFabric.FabricTransport.Internal" Version="8.7.157" />
    </ItemGroup>

</Project>
