<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;netcoreapp3.0</TargetFrameworks>
        <Description>Kestrel support for ASP.Net Core with Autofac.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Cogito.ServiceFabric.AspNetCore.Autofac\Cogito.ServiceFabric.AspNetCore.Autofac.csproj" />
        <ProjectReference Include="..\Cogito.ServiceFabric.AspNetCore.Kestrel\Cogito.ServiceFabric.AspNetCore.Kestrel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.ServiceFabric" Version="11.7.157" />
      <PackageReference Include="Microsoft.ServiceFabric.Data" Version="8.7.157" />
      <PackageReference Include="Microsoft.ServiceFabric.Data.Extensions" Version="8.7.157" />
      <PackageReference Include="Microsoft.ServiceFabric.FabricTransport.Internal" Version="8.7.157" />
    </ItemGroup>

</Project>
